function y = ode2(x,u)
  y = zeros(2,1);
  y(1) = u(2);
  y(2) = 2 * x * tan(x) * atan(x) / (1 + x^2) ...
        - cos(x)...
        - 2 * x / (1 + x^2) * u(2)...
        - 2 * x * tan(x) / (1 + x^2) * u(1);
end
